create table tb_sales (id int8 generated by default as identity, amount float8, date date, deals int4, visited int4, seller_id int8, primary key (id));
create table tb_sellers (id int8 generated by default as identity, name varchar(255), primary key (id));
alter table if exists tb_sales add constraint FKp0nn0oixeiw2fq3jivj6vnsu foreign key (seller_id) references tb_sellers;


postgres://

lclrdpeyriwyfv

:

9c99ffaf21565ef3feed285fd82ec11efdbd3c0d53ad8cb2881d986cbd28917d

@

ec2-52-21-252-142.compute-1.amazonaws.com
:
5432
/
d3oekiqiff92j

